teste = input("Digite algo: ")
print()
print(f'O tipo deste valor é {type(teste)}.')
print(f'É alfanumérico? {teste.isalnum()}')
print(f'É alfabético? {teste.isalpha()}')
print(f'Está em minúsculo? {teste.islower()}')
print(f'Está em maiúsculo? {teste.isupper()}')
print(f'É um número? {teste.isnumeric()}')
print(f'Só tem espaço? {teste.isspace()}')
print(f'Está capitalizado?(primeira letra em maiúscula) {teste.istitle()}')
